### PR TITLE
Fix keyboard layout applet height

### PR DESCRIPTION
**Pull request by PlugaruT**
#7 fixed

### CODE REVIEW

**Comment by zagortenay333** [comment]
Thx

**Comment by zagortenay333** [comment]
Oh noes...

I just noticed you only edited the css file. You should have edited the sass file and compiled to css. Oh well, doesn't matter; I'll do it later.

**Comment by PlugaruT** [comment]
Oh, sorry, I didn't read your contributing.md file. I had to be more careful.

> On Dec 24 2015, at 1:52 pm, zagortenay333 &lt;notifications@github.com&gt;
wrote:  

>

> Oh noes...

>

> I just noticed you only edited the css file. You should have edited the sass
file and compiled to css. Oh well, doesn't matter; I'll do it later.

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/zagortenay333/numix-cinnamon/pull/8#issuecomment-16
7099048).

**Comment by zagortenay333** [comment]
Np

**Comment by zagortenay333** [comment]
Ok, I've hard reset this pull. You can do it again. Just make sure you also hard reset your commit!

**Pull request merged**
