### PR TITLE
Update project files

### PR DESCRIPTION
**Pull request by stevelacy**
- remove .nvmrc as it is a per-user file and only used by a small set of node.js devs
- remove depreciated `gulp.start`
- add missing fields to `package.json` to fix npm errors

### CODE REVIEW

**Comment by zagortenay333** [comment]
* Not sure I understand the reason behind removing nvmrc?

* `gulp.start` is not yet deprecated. I'll  use it 'till gulp v4 allows for proper sequencing.

* I don't wanna  add that stuff to the `package.json`; it seems redundant. You'd usually do it if you are making an npm package.

* Not sure why I need to add all those extensions in the `.gitignore` file? Seems completely random in this project.

**Comment by stevelacy** [comment]
- A .nvmrc file is a per user choice for the node version, your project should *not* change the version of node used. Instead you should add a `engines` parameter to your package.json. Plus most users do not use nvm.
 - There is no reason to use gulp.start in a sequenced task list, switching to a array (as per docs) reduces the code with the same result while it does not have issues with depreciating.

- You don't want to fix npm errors? It is not redundant and correctly adds the information for your project.

- Have you ever had a PR from someone with some random `.log`, `sublime.project`, `.Trash-1000`, `.Ds_Store`, file? Adding those params removes the chance of you or others from adding unwanted files to the git commit.

**Comment by zagortenay333** [comment]
Still don't understand that `.nvmrc` point. What does the `engine` parameter do that `.nvmrc` doesn't? They both tell you what version of node you need for this project.

The reason I'm using `gulp.start` is because the `reloadTheme` task is run in a callback.

**Comment by stevelacy** [comment]
the `.nvmrc` is not supported by node or npm. Just a third party node manager. Using the engines parameter will show an error when a user tries to use an unsupported version of node.

If you want the task to be run last: https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md

**Comment by zagortenay333** [comment]
The point about getting an error is useful, but I just tried it, and I'm not getting any errors. Weird.

I need a sequence without making task dependencies though.

**Comment by zagortenay333** [comment]
From what I see the `engine` parameter will only throw an error if you are installing a package while not having the required node version. If you are just installing the deps from withing the `package.json`, then it won't.

**Comment by zagortenay333** [comment]
Closing this.

* No point in removing `.nvmrc`

**Comment by stevelacy** [comment]
lol.

You have a lot to learn about open source.

**Comment by zagortenay333** [comment]
Excuse me?

**Pull request closed without merging**
